# Generated by Django 5.2.1 on 2025-05-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.FilePathField(path='/Users/arturboev/Documents/ads_crm/base/mediaimages/')),
                ('category', models.CharField(choices=[('Вещи для дома', 'Household Items'), ('Одежда', 'Clothes'), ('Транспорт', 'Transport')])),
                ('condition', models.CharField(choices=[('новый', 'New'), ('б/у', 'Used')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('ожидает', 'Awaiting'), ('принята', 'Accepted'), ('отклонена', 'Rejected')])),
            ],
        ),
    ]
