# Generated by Django 5.2.1 on 2025-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('ожидает', 'Awaiting'), ('принято', 'Accepted'), ('отклонено', 'Rejected')], default='ожидает'),
        ),
    ]
