# Generated by Django 5.2.1 on 2025-05-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('вещи для дома', 'Household Items'), ('одежда', 'Clothes'), ('транспорт', 'Transport')]),
        ),
    ]
