# Generated by Django 5.2.1 on 2025-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('вещи для дома', 'вещи для дома'), ('одежда', 'одежда'), ('транспорт', 'транспорт')]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('новый', 'новый'), ('б/у', 'б/у')]),
        ),
    ]
